/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"

// establece la codificación del sistema al programa
#include "autolocale.h"

//  librerias importadas por el profesor
// #include <stdlib.h>
// #include <time.h>
// #include <string.h>
// #include <stdio.h>
#include <ctype.h>

#define Cls system("clear")
#define Pause system("read -p \"Pulsa la tecla return para continuar..... \" a")
#define MostrarAviso(Texto) \
	{                       \
		printf(Texto);      \
		Pause;              \
	}
// ******************************************** Variables globales ********************************************
int ida = -1;
// ******************************************** MENUS ********************************************

/**
 * @brief Muestra el menú principal de la aplicación y captura la opción del usuario.
 *
 * Presenta las opciones básicas (Administración, Consulta, Préstamo, Devolución)
 * e impide que el usuario introduzca una opción fuera de rango.
 *
 * @return Opción seleccionada por el usuario (entero entre 0 y 4).
 */
int MenuPrincipal()
{
	int Salida;
	do
	{
		Cls;
		printf(" GESTOR BIBLIOTECARIO 1.0 (M. PRINCIPAL)\n");
		printf("*****************************************\n");
		printf("\t1.- M. Administración\n");
		printf("\t2.- Consulta de libros\n");
		printf("\t3.- Préstamo de libros\n");
		printf("\t4.- Devolución de libros\n");
		printf("\t0.- Salir\n\n");
		printf(" Elige opción: ");
		scanf("%d", &Salida);
		if (Salida < 0 || Salida > 4)
			MostrarAviso("\n\n *** Error en la entrada de Datos.***\n\n");
	} while (Salida < 0 || Salida > 4);
	return Salida;
}

/**
 * @brief Despliega el menú de administración y lee la opción seleccionada.
 *
 * Muestra opciones como cargar datos, nuevo libro, comprar, etc., y se asegura
 * de devolver un valor dentro de los límites esperados.
 *
 * @return Opción elegida por el administrador (entero entre 0 y 8).
 */
int MenuAdministracion()
{
	int Salida;
	do
	{
		Cls;
		printf(" GESTOR BIBLIOTECARIO 1.0 (M. ADMINISTRACION)\n");
		printf("**********************************************\n");
		printf("\t1.- Cargar datos Biblioteca\n");
		printf("\t2.- Guardar datos Biblioteca\n");
		printf("\t3.- Nuevo libro\n");
		printf("\t4.- Comprar libros\n");
		printf("\t5.- Retirar libros\n");
		printf("\t6.- Ordenar libros\n");
		printf("\t7.- Buscar libros\n");
		printf("\t8.- Listar libros\n");
		printf("\t0.- Salir\n\n");
		printf(" Elige opción: ");
		scanf("%d", &Salida);
		if (Salida < 0 || Salida > 8)
			MostrarAviso("\n\n *** Error en la entrada de Datos.***\n\n");
	} while (Salida < 0 || Salida > 8);
	return Salida;
}

// ******************************************** funciones auxiliares ********************************************

/**
 * @brief Formatea un texto a un ancho determinado rellenando con un carácter.
 *
 * Utilizada para alinear texto en consola, asumiendo ciertas longitudes de las
 * cadenas y tratando caracteres extendidos (como UTF-8).
 *
 * @param[out] Salida    Cadena donde se devolverá el resultado formateado.
 * @param[in]  Texto     Cadena de entrada original.
 * @param[in]  Ancho     Anchura final esperada.
 * @param[in]  Caracter  Carácter empleado para rellenar los espacios restantes.
 */
void Formatea(char *Salida, const char *Texto, int Ancho, char Caracter)
{
	Cadena Vacia;
	int len = Ancho - strlen(Texto);
	int l = 0, c = 0;

	while (Texto[l] != '\0')
	{
		if ((unsigned char)Texto[l] > 128)
			c++;
		l++;
	}
	len += c / 2;

	if (len < 0)
		len = 0;
	for (int i = 0; i < len; i++)
		Vacia[i] = Caracter;
	Vacia[len] = '\0';

	sprintf(Salida, "%s%s", Texto, Vacia);
}

/**
 * @brief Muestra tabulados los campos de un libro con opción a imprimir la cabecera.
 *
 * Emplea funciones de formato de texto para imprimir ordenadamente la tabla
 * de libros y su correspondiente fila.
 *
 * @param[in] L         Puntero a la estructura TLibro que se va a mostrar.
 * @param[in] Pos       Índice o posición del libro en la lista (indexado desde 0).
 * @param[in] Cabecera  Si es TRUE, imprime los nombres de las columnas antes del libro.
 */
void MostrarLibro(TLibro *L, int Pos, bool_t Cabecera)
{
	Cadena T, A, B, PI;
	if (Cabecera == TRUE)
	{
		printf("%-*s%-*s%-*s%*s%*s%*s\n", 5, "POS", 58, "TITULO", 18, "ISBN", 4, "DIS", 4, "PRE", 4, "RES");
		printf("     %-*s%-*s%-*s\n", 30, "AUTOR", 28, "PAIS (IDIOMA)", 12, "AÑO");
		Formatea(B, "*", 93, '*');
		printf("%s\n", B);
	}
	Formatea(T, L->Titulo, 58, ' ');
	Formatea(A, L->Autor, 30, ' ');
	strcpy(B, L->Pais);
	strcat(B, "(");
	strcat(B, L->Idioma);
	strcat(B, ")");
	Formatea(PI, B, 28, ' ');
	printf("%-5d%s%-*s%*d%*d%*d\n", Pos + 1, T, 18, L->Isbn, 4, L->NoLibros, 4, L->NoPrestados, 4, L->NoListaEspera);
	printf("     %s%s%-*d\n", A, PI, 12, L->Anio);
}

/**
 * @brief Comprueba si el texto especificado existe dentro de un campo del libro.
 *
 * Busca de forma estricta o total ('*') si la sub-cadena `Texto`
 * aparece en un campo (ISBN, título, autor...). Resulta fundamental para la
 * implementación de búsquedas.
 *
 * @param[in] L      Puntero a estructura TLibro sobre el que se va a buscar.
 * @param[in] Texto  Sub-cadena de la cual se desea comprobar la ocurrencia.
 * @param[in] Campo  Letra que indica el filtro a aplicar:
 *                   - 'i': ISBN, 't': Título, 'a': Autor, 'p': País, 'd': Idioma, '*': Cualquier campo.
 * @return           TRUE si contiene el texto indicado, o FALSE en caso contrario.
 */
bool_t Comprobar(TLibro *L, Cadena Texto, char Campo)
{
	bool_t Encontrado = FALSE;
	switch (tolower(Campo))
	{
	case 'i':
		Encontrado = strstr(L->Isbn, Texto) != NULL ? TRUE : FALSE;
		break;
	case 't':
		Encontrado = strstr(L->Titulo, Texto) != NULL ? TRUE : FALSE;
		break;
	case 'a':
		Encontrado = strstr(L->Autor, Texto) != NULL ? TRUE : FALSE;
		break;
	case 'p':
		Encontrado = strstr(L->Pais, Texto) != NULL ? TRUE : FALSE;
		break;
	case 'd':
		Encontrado = strstr(L->Idioma, Texto) != NULL ? TRUE : FALSE;
		break;
	case '*':
		Encontrado = (strstr(L->Isbn, Texto) != NULL || strstr(L->Titulo, Texto) != NULL || strstr(L->Autor, Texto) != NULL ||
					  strstr(L->Pais, Texto) != NULL || strstr(L->Idioma, Texto) != NULL)
						 ? TRUE
						 : FALSE;
	}
	return Encontrado;
}

/**
 * @brief Comprueba que la respuesta de una llamada RPC no sea NULL.
 *
 * Si es nula, significa que hubo un error de comunicación RPC, por lo que
 * se informa al usuario mediante clnt_perror sobre el fallo antes de volver
 * a la rutina normal.
 *
 * @param[in] resultado Puntero con el resultado estático de una llamada RPC.
 * @param[in] clnt      Puntero opaco al handle del cliente (struct CLIENT).
 * @return              TRUE si `resultado` es distinto de NULL, FALSE en caso contrario.
 */
bool_t comprueba_llamada(void *resultado, CLIENT *clnt)
{
	if (resultado == NULL)
	{
		clnt_perror(clnt, "call failed");
		return FALSE;
	}
	return TRUE;
}

// ******************************************** manejar servicios ********************************************

/**
 * @brief Gestiona la desconexión del administrador enviando la petición al servidor.
 *
 * Se invoca a `desconexion_1` usando el ID global `ida`. Si tiene éxito,
 * reinicia la variable a `-1`.
 *
 * @param[in,out] clnt  Handle del cliente RPC (struct CLIENT).
 */
static void maneja_desconexion(CLIENT *clnt)
{
	bool_t *resultado;
	if (ida == -1)
		return;

	resultado = desconexion_1(&ida, clnt);
	if (!comprueba_llamada(resultado, clnt))
		return;

	if (*resultado)
	{
		ida = -1;
		MostrarAviso("Admin desconectado con éxito.\n");
	}
	else
		MostrarAviso("Error desconectando admin");
}

static void maneja_carga_datos(CLIENT *clnt)
{

	// Comprobamos si el servidor tiene libros para avisar que se sobreescribe
	// int *num_libros = nlibros_1(&ida, clnt);
	int num_libros = 1;
	// if (num_libros != NULL && *num_libros > 0)
	if (num_libros == 1) // TODO CAMBIAR cuando implemente nlibros en servidor
	{
		char respuesta;
		printf("CUIDADO. Ya hay %d datos cargados, si continúa sobreescribirá los datos existentes.\n", num_libros);
		printf("¿Desea continuar (s/N)?: ");
		scanf(" %c", &respuesta);

		// cualquier cosa que no sea 'S' o 's' se toma como un no
		if (tolower(respuesta) != 's')
		{
			printf("Operación abortada\n");
			Pause;
			return;
		}
	}

	// cargamos datos

	Cadena nombre_fichero;
	TFichero parametros_fichero;

	// pedimos nombre fichero
	printf("Introduzca nombre del fichero a cargar: ");
	scanf("%s", parametros_fichero.NomFile);

	// Si se llama desde menú admin no debería 'ida' ser -1 -> no lo controlo
	// if (ida == -1)...
	parametros_fichero.Ida = ida;

	int *resultado = cargardatos_1(&parametros_fichero, clnt);

	if (!comprueba_llamada(resultado, clnt))
		return;

	switch (*resultado)
	{
	case 1:
		printf("Datos cargados y ordenados correctamente.\n");
		break;
	case 0:
		printf("Error abriendo fichero o error de memoria dinámica.\n");
		break;
	case -1:
		printf("No hay administrador válido o Ida no coincide con el servidor.\n");
		break;
	}
}

static void maneja_guarda_datos(CLIENT *clnt)
{
	char respuesta;
	printf("ATENCIÓN. Guardando el archivo sobreescribirá los datos existentes en él.\n");
	printf("¿Desea continuar (s/N)?: ");
	scanf(" %c", &respuesta);

	// cualquier cosa que no sea 'S' o 's' se toma como un no
	if (tolower(respuesta) != 's')
	{
		printf("Operación abortada\n");
		Pause;
		return;
	}

	// guardamos datos
	bool_t *resultado = guardardatos_1(&ida, clnt);

	if (!comprueba_llamada(resultado, clnt))
		return;

	if (*resultado)
		printf("Archivo guardado con éxito\n");
	else
	{
		printf("Error. Posibles errores: \n- Id admin incorrecta o No hay administrador válido.\n");
		printf("- No hay fichero abierto.\n- Error abriendo o escribiendo archivo.\n");
	}
}

/**
 * @brief Implementa el bucle de opciones de administración y lanza las peticiones.
 *
 * Muestra el menú de administración del sistema repetidamente. Ante cada opción
 * realiza las acciones y llamadas RPC correspondientes hasta elegir 0 (desconectar).
 *
 * @param[in,out] clnt Handle del cliente para comunicación RPC (struct CLIENT).
 */
static void maneja_menu_admin(CLIENT *clnt)
{
	int opcion;

	do
	{
		opcion = MenuAdministracion();
		switch (opcion)
		{
		case 1:

			maneja_carga_datos(clnt);
			break;

		case 2:

			maneja_guarda_datos(clnt);
			break;

		case 3:
			// TODO nuevo libro
			break;
		case 4:
			// TODO comprar libros
			break;
		case 5:
			// TODO retirar libros
			break;
		case 6:
			// TODO ordenar libros
			break;
		case 7:
			// TODO buscar libros
			break;
		case 8:
			// TODO listar libros
			break;
		case 0:
			maneja_desconexion(clnt);
			break;
		default:
			break;
		}

	} while (opcion != 0);
}

/**
 * @brief Gestiona la conexión del administrador solicitando clave de acceso.
 *
 * Muestra el prompt, lee la clave, llama a la función `conexion_1` del
 * servidor y si recibe un id válido establece la variable global `ida`.
 *
 * @param[in,out] clnt El handle del cliente para RPC (struct CLIENT).
 */
static void maneja_conexion(CLIENT *clnt)
{
	int *resultado;
	// pedir clave
	// Cadena clave;
	// printf("Introduzca la contraseña de asdministrador: ");
	// scanf("%s", clave);

	// TODO descomentar solicitar por teclado contraseña cuando todo esté acabado
	Cadena clave = "12";

	resultado = conexion_1(clave, clnt);
	if (!comprueba_llamada(resultado, clnt))
		return;

	switch (*resultado)
	{
	case -1:
		MostrarAviso("Error. Ya hay un usuario identificado como administrador.\n");
		break;
	case -2:
		MostrarAviso("Error. Contraseña incorrecta.\n");
		break;
	default:
		MostrarAviso("Accediendo a menú administración.\n");
		ida = *resultado;
		maneja_menu_admin(clnt);
		break;
	}
}

/**
 * @brief Función esqueleto generada por rpcgen para probar las llamadas.
 *
 * Contiene un bloque de pruebas estandarizado. No es llamado obligatoriamente
 * durante el ciclo de vida real del cliente, pero es ilustrativo de los tipos
 * y argumentos que requiere cada llamada RPC.
 *
 * @param[in] host Puntero a cadena con la dirección/host del servidor RPC.
 */
void gestorbiblioteca_1(char *host)
{
	CLIENT *clnt;
	int *result_1;
	char conexion_1_arg;
	bool_t *result_2;
	int desconexion_1_arg;
	int *result_3;
	TFichero cargardatos_1_arg;
	bool_t *result_4;
	int guardardatos_1_arg;
	int *result_5;
	TNuevo nuevolibro_1_arg;
	int *result_6;
	TComRet comprar_1_arg;
	int *result_7;
	TComRet retirar_1_arg;
	bool_t *result_8;
	TOrdenacion ordenar_1_arg;
	int *result_9;
	int nlibros_1_arg;
	int *result_10;
	TConsulta buscar_1_arg;
	TLibro *result_11;
	TPosicion descargar_1_arg;
	int *result_12;
	TPosicion prestar_1_arg;
	int *result_13;
	TPosicion devolver_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, "tcp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	result_1 = conexion_1(&conexion_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_2 = desconexion_1(&desconexion_1_arg, clnt);
	if (result_2 == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_3 = cargardatos_1(&cargardatos_1_arg, clnt);
	if (result_3 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_4 = guardardatos_1(&guardardatos_1_arg, clnt);
	if (result_4 == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_5 = nuevolibro_1(&nuevolibro_1_arg, clnt);
	if (result_5 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_6 = comprar_1(&comprar_1_arg, clnt);
	if (result_6 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_7 = retirar_1(&retirar_1_arg, clnt);
	if (result_7 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_8 = ordenar_1(&ordenar_1_arg, clnt);
	if (result_8 == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_9 = nlibros_1(&nlibros_1_arg, clnt);
	if (result_9 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_10 = buscar_1(&buscar_1_arg, clnt);
	if (result_10 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_11 = descargar_1(&descargar_1_arg, clnt);
	if (result_11 == (TLibro *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_12 = prestar_1(&prestar_1_arg, clnt);
	if (result_12 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_13 = devolver_1(&devolver_1_arg, clnt);
	if (result_13 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

/**
 * @brief Punto de entrada del cliente RPC al gestor de la biblioteca.
 *
 * Crea la comunicación RPC a través de `clnt_create`. Inicia el
 * bucle del menú principal del usuario.
 *
 * @param[in] argc Cantidad de argumentos pasados por consola.
 * @param[in] argv Array de cadenas desde terminal. Debe incluir `host`.
 * @return         Retorna 0 si la ejecución finaliza con éxito.
 */
int main(int argc, char *argv[])
{

	// ------------------------ iniciar conexcion ------------------------

	// Comprobamos si ha pasado un argumento de ejecución
	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}

	// obtenemos host desde argumento de ejecución
	char *host = argv[1];

	CLIENT *clnt = clnt_create(host, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, "tcp");

	// Controlar fallo al crear
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
	MostrarAviso("Conexión con el servidor exitosa\n");

	// ------------------------ Ejecucion menu ------------------------

	// variables
	int *resultado_rpc;
	int opcion;
	int idAdmin;

	do
	{

		opcion = MenuPrincipal();
		switch (opcion)
		{
		case 1:
			maneja_conexion(clnt);
			break;
		case 2:
			break;

		default:
			// MenuPrincipal() ya controla que opcion esté acotada a las opciones del switch
			break;
		}

	} while (opcion != 0);

	clnt_destroy(clnt);
	exit(0);
}
