/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"


// establece la codificación del sistema al programa
#include "autolocale.h"

// ************************************ Variables globales ************************************
TLibro *Biblioteca=NULL; //Vector dinámico de libros
int NumLibros=0; //Número de libros almacenados en el vector dinámico.
int Tama=0; //Tamaño del vector dinámico. El incremento será por bloques de 4 libros.
int IdAdmin=-1; //Identificador de Administración enviado al usuario.
Cadena NomFichero=""; //Nombre del último fichero binario que se ha cargado en memoria.
int CampoOrdenacion=0; //Campo de ordenación por que se ordenarán los libros.




int *
conexion_1_svc(char *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
desconexion_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
cargardatos_1_svc(TFichero *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
guardardatos_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nuevolibro_1_svc(TNuevo *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
comprar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retirar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
ordenar_1_svc(TOrdenacion *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nlibros_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
buscar_1_svc(TConsulta *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

TLibro *
descargar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static TLibro  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
prestar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
devolver_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
