/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
// Para resolver el error "rpc/rpc.h no encontrado" (una dependencia de gestorAlmacenes.h):
// Asegúrese de que la ruta de inclusión de su compilador apunte a los encabezados de la biblioteca RPC
// (por ejemplo, de libtirpc). Esto es una configuración del entorno de compilación.
#include "gestorAlmacenes.h"

// Variable global para el nombre del almacén actual
char nombre_almacen_actual[90] = "";




// Declaración de la función mostrar_menu
int mostrar_menu();

// Método que limpia buffer de teclado
void limpiaBuffer();

// Función supermercado_1 generada por rpcgen, comentada ya que no se usará directamente.
void supermercado_1(char *host)
{
	/*
	CLIENT *clnt;
	TDatosAlmacen *result_1;
	int datosalmacen_1_arg;
	int *result_2;
	int nproductos_1_arg;
	int *result_3;
	TDatosAlmacen crearalmacen_1_arg;
	int *result_4;
	char abriralmacen_1_arg; // Debería ser Cadena? Revisar tipo original
	bool_t *result_5;
	int guardaralmacen_1_arg;
	bool_t *result_6;
	int cerraralmacen_1_arg;
	bool_t *result_7;
	int almacenabierto_1_arg;
	int *result_8;
	TBusProd buscaproducto_1_arg;
	TProducto *result_9;
	TObtProd obtenerproducto_1_arg;
	bool_t *result_10;
	TActProd anadirproducto_1_arg;
	bool_t *result_11; // Falta la llamada a ActualizarProducto
	TBusProd eliminarproducto_1_arg;
	TProducto *result_12; // Corresponde a operacion_1
	TOperacion operacion_1_arg;


#ifndef DEBUG
	clnt = clnt_create(host, SUPERMERCADO, SUPERMERCADO_VER, "udp"); // Originalmente UDP
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif // DEBUG //

	// ... llamadas RPC de ejemplo originales ...
	// result_1 = datosalmacen_1(&datosalmacen_1_arg, clnt);
	// ... etc ...

#ifndef DEBUG
	clnt_destroy(clnt);
#endif // DEBUG //
	*/
}

// Función principal del cliente
int main(int argc, char *argv[])
{
	char *host;
	CLIENT *clnt;
	int opcion;
	// Variable para almacenar el ID del almacén actual gestionado por este cliente
	int id_almacen_actual = -1; // -1 indica que no hay almacén abierto

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];

	// Crear cliente RPC usando TCP
#ifndef DEBUG
	clnt = clnt_create(host, SUPERMERCADO, SUPERMERCADO_VER, "tcp"); // Cambiado a TCP
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	do
	{
		opcion = mostrar_menu();

		switch (opcion)
		{
		case 1:
			printf("Has elegido: Crear un almacén vacio\n");
			if (id_almacen_actual != -1)
			{
				printf("Error: Ya hay un almacén abierto (%s). Ciérralo primero.\n",
					   nombre_almacen_actual);
				break;
			}

			TDatosAlmacen nuevo_almacen_datos;
			

			// Solicitar datos al usuario
			printf("Introduce el nombre del almacén: ");
			fgets(nuevo_almacen_datos.Nombre, sizeof(nuevo_almacen_datos.Nombre), stdin);
			nuevo_almacen_datos.Nombre[strcspn(nuevo_almacen_datos.Nombre, "\n")] = '\0';
			// con scanf solo conseguimos la primera cadena antes del espacio
			//scanf("%s",nuevo_almacen_datos.Nombre); 

			printf("Introduce la dirección del almacén: ");
			fgets(nuevo_almacen_datos.Direccion, sizeof(nuevo_almacen_datos.Direccion), stdin);
			nuevo_almacen_datos.Direccion[strcspn(nuevo_almacen_datos.Direccion, "\n")] = '\0';

			printf("Introduce el nombre del fichero para el almacén (ej: mi_almacen.dat): ");
			fgets(nuevo_almacen_datos.Fichero, sizeof(nuevo_almacen_datos.Fichero), stdin);
			nuevo_almacen_datos.Fichero[strcspn(nuevo_almacen_datos.Fichero, "\n")] = '\0';

			// Llamada RPC
			int *resultado_rpc = crearalmacen_1(&nuevo_almacen_datos, clnt);
			if (resultado_rpc == NULL)
			{
				clnt_perror(clnt, "Error RPC CrearAlmacen");
			}
			else
			{
				int id_obtenido = *resultado_rpc;
				if (id_obtenido == -1)
				{
					printf("Error en el servidor al crear el almacén. Comprueba permisos y espacio.\n");
				}
				else if (id_obtenido == -2)
				{
					printf("El fichero '%s' ya existe. Usa la opción 'Abrir un fichero de almacén'.\n",
						   nuevo_almacen_datos.Fichero);
				}
				else
				{
					// Éxito: actualizar estado cliente
					id_almacen_actual = id_obtenido;
					strncpy(nombre_almacen_actual,
							nuevo_almacen_datos.Nombre,
							sizeof(nombre_almacen_actual) - 1);
					nombre_almacen_actual[sizeof(nombre_almacen_actual) - 1] = '\0';
					printf("Almacén '%s' creado/abierto con éxito. ID: %d\n",
						   nombre_almacen_actual, id_almacen_actual);
				}
			}

			break;
		case 2:{
			printf("Has elegido: Abrir un fichero de almacén\n");
			// Aquí irán las llamadas RPC correspondientes
			// Ejemplo: Llamar a una función local que pida nombre fichero y llame a abriralmacen_1
		}
			
			break;
		case 3:
			printf("Has elegido: Cerrar un almacén\n");
			// Aquí irán las llamadas RPC correspondientes
			// Ejemplo: Llamar a cerraralmacen_1 si id_almacen_actual != -1
			break;
		case 4:
			printf("Has elegido: Guardar Datos\n");
			// Aquí irán las llamadas RPC correspondientes
			// Ejemplo: Llamar a guardaralmacen_1 si id_almacen_actual != -1
			break;
		case 5:
			printf("Has elegido: Listar productos del almacén\n");
			// Aquí irán las llamadas RPC correspondientes
			// Ejemplo: Llamar a nproductos_1 y luego bucle con obtenerproducto_1
			break;
		case 6:
			printf("Has elegido: Añadir un producto\n");
			// Aquí irán las llamadas RPC correspondientes
			// Ejemplo: Llamar a una función local que pida datos producto y llame a anadirproducto_1
			break;
		case 7:
			printf("Has elegido: Actualizar un producto\n");
			// Aquí irán las llamadas RPC correspondientes
			// Ejemplo: Llamar a una función local que pida código, busque, pida nuevos datos y llame a actualizarproducto_1
			break;
		case 8:
			printf("Has elegido: Consultar un producto\n");
			// Aquí irán las llamadas RPC correspondientes
			// Ejemplo: Llamar a una función local que pida código, llame a buscaproducto_1 y obtenerproducto_1
			break;
		case 9:
			printf("Has elegido: Eliminar un producto\n");
			// Aquí irán las llamadas RPC correspondientes
			// Ejemplo: Llamar a una función local que pida código y llame a eliminarproducto_1
			break;
		case 0:
			printf("Saliendo del programa...\n");
			// Considerar cerrar el almacén si está abierto antes de salir?
			// if (id_almacen_actual != -1) { /* llamar a cerraralmacen_1 */ }
			break;
		default:
			printf("Opción no válida. Inténtalo de nuevo.\n");
			break;
		}

		// Pausa antes de volver a mostrar el menú (excepto si se elige salir)
		if (opcion != 0)
		{
			printf("\nPulsa Enter para continuar...");
			// Consumir el Enter pendiente del scanf anterior y esperar nuevo Enter
			// while (getchar() != '\n'); // Limpia buffer si quedó algo
			fflush(stdin); // Limpiamos buffer
			getchar();	   // Espera el Enter del usuario
		}

	} while (opcion != 0);

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */

	exit(0);
}

/**
 * Función para mostrar el menú de opciones al usuario.
 * Permite seleccionar diferentes acciones relacionadas con el almacén.
 * 
 * Controla errores relacionados con teclas incorrectas. 
 * Solo devuelve opciones válidas
 * 
 * @return int Opción seleccionada por el usuario.
 */
int mostrar_menu()
{
	int opcion;

	// Limpiar pantalla
	system("clear");

	printf("\n");
	printf("****************************************\n");
	// Mostrar el nombre del almacén actual si existe
	if (strlen(nombre_almacen_actual) > 0)
	{
		printf("--- Menú Almacenes --- %s ---\n", nombre_almacen_actual);
	}
	else
	{
		printf("--- Menú Almacenes --- (Ningún almacén abierto) ---\n");
	}
	printf("****************************************\n");
	printf("1. Crear un almacén vacio.\n");
	printf("2. Abrir un fichero de almacén.\n");
	printf("3. Cerrar un almacén.\n");
	printf("4. Guardar Datos.\n");
	printf("5. Listar productos del almacén.\n");
	printf("6. Añadir un producto.\n");
	printf("7. Actualizar un producto.\n");
	printf("8. Consultar un producto.\n");
	printf("9. Eliminar un producto.\n");
	printf("0. Salir.\n");
	printf("****************************************\n");
	printf("Introduce tu opción: ");

	// Leer la opción del usuario
	// Validar que se introduce un entero dentro del rango "correcto"
	while (scanf("%d", &opcion) != 1 || opcion < 0 || opcion > 9) //scanf devuelve 1 si la entrada es correcta
	{
		// Nos aseguramos que la entrada sea correcta y este en rango
		printf("Entrada inválida. Introduce un número válido: ");
		// Limpiar el buffer de entrada
		int aux;
		limpiaBuffer();
			
			

		// No sirve en linux 
		// fflush(stdin);
	}

	// Limpiar el buffer del teclado después de leer el entero correctamente
	limpiaBuffer();

	return opcion;
}


/**
 * Función para limpiar el buffer de entrada.
 * Elimina cualquier carácter sobrante hasta el final de la línea.
 */
void limpiaBuffer()
{
    int c;
    while ((c = getchar()) != '\n' && c != EOF) { }
}